# Copyright 2015 Adam Green (http://mbed.org/users/AdamGreen/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
PROJECT         := HelloWorld
DEVICES         := DISCO_F407VG \
                   DISCO_F429ZI \
                   KL25Z \
                   LPC1768 \
                   LPC11C24 \
                   LPC11U24 \
                   LPC4330_M4 \
                   NRF51822 \
                   NUCLEO_F401RE \
                   NUCLEO_F411RE \
                   NUCLEO_F446RE \
                   B96B_F446VE \
                   NUCLEO_F072RB \
                   NUCLEO_F103RB \
                   NUCLEO_L053R8
GCC4MBED_DIR    := ../..
NO_FLOAT_SCANF  := 1
NO_FLOAT_PRINTF := 1

include $(GCC4MBED_DIR)/build/gcc4mbed.mk
